CREATE TABLE [SME].[litigation_records] (
    [Name of the Client]                  VARCHAR (255) NULL,
    [CIF]                                 VARCHAR (255) NULL,
    [AccountNumber]                       VARCHAR (255) NULL,
    [RelatedAccount_Others]               VARCHAR (255) NULL,
    [Branch]                              VARCHAR (255) NULL,
    [Branch Code]                         INT           NULL,
    [Nature of Suit]                      VARCHAR (255) NULL,
    [Suit No]                             VARCHAR (255) NULL,
    [Suit Filing Date]                    DATETIME      NULL,
    [Cheque Number]                       VARCHAR (255) NULL,
    [Suit Value]                          FLOAT (53)    NULL,
    [Value in Lacs]                       FLOAT (53)    NULL,
    [Plaintiff]                           VARCHAR (255) NULL,
    [PlaintiffCIF]                        VARCHAR (255) NULL,
    [PRODUCT_CATEGORY]                    VARCHAR (255) NULL,
    [Division]                            VARCHAR (255) NULL,
    [Unit]                                VARCHAR (255) NULL,
    [Law Firm]                            VARCHAR (255) NULL,
    [Law Firm CIF]                        VARCHAR (255) NULL,
    [Present Case Status]                 VARCHAR (255) NULL,
    [Last Hearing Date]                   DATETIME      NULL,
    [Next Hearing Date]                   DATETIME      NULL,
    [Session No/ ARA No]                  VARCHAR (255) NULL,
    [Court No]                            VARCHAR (255) NULL,
    [Collection from Suit Filing date to] FLOAT (53)    NULL,
    [Aging]                               INT           NULL,
    [Previous Hajira Dates]               VARCHAR (255) NULL,
    [CaseID]                              INT           NULL,
    [SyncDate]                            DATETIME      NULL,
    [Date]                                DATE          NULL
);